name: Shell
on:
  push:
    branches:
    - main
    paths:
    - '**.sh'
  pull_request:
    paths:
    - '**.sh'
jobs:
  shellcheck:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout current git repository
      uses: actions/checkout@v2
    - name: Run ShellCheck
      uses: ludeeus/action-shellcheck@1.1.0
